#!/bin/sh

lein localrepo install lib/opengrok.jar org.opensolaris/opengrok 0.13-rc8
lein localrepo install lib/jrcs.jar org.opensolaris/opengrok.jrcs 0.13.0
lein bin

# emacs
echo "#!/usr/bin/env sh" | cat - target/clj-opengrok > clj-opengrok && chmod +x clj-opengrok
# windows
cp -a target/clj-opengrok clj-opengrok.bat
