#!/bin/sh

lein localrepo install lib/opengrok-1.7.42.jar org.opengrok/opengrok 1.7.42
lein bin

# emacs
echo "#!/usr/bin/env sh" | cat - target/clj-opengrok > clj-opengrok && chmod +x clj-opengrok
# windows
cp -a target/clj-opengrok clj-opengrok.bat
